CREATE TABLE [dbo].CardsIssued(
[MatchId] BIGINT NOT NULL,
[PlayerId] UNIQUEIDENTIFIER NOT NULL,
[TypeId] INTEGER NOT NULL,  --LINK to ENUM RED/YELLOW
[DateCreated] DATETIME NOT NULL DEFAULT GETDATE())
GO