CREATE TABLE [dbo].[Club](
[Id] UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() NOT NULL,
[Name] NVARCHAR(2000) NOT NULL,
[PhoneNumber] NVARCHAR(250) NULL,
[Badge] VARBINARY NULL,
[Address] NVARCHAR(2000) NOT NULL,
[gpsLocation] NVARCHAR(200) NULL,
[StadiumId] UNIQUEIDENTIFIER NOT NULL,
[URL] NVARCHAR(1500) NULL,
[IsHome] BIT NOT NULL DEFAULT 0,
[DateCreated] DATETIME NOT NULL DEFAULT GETDATE())
GO