CREATE TABLE [dbo].[CoachDetails](
[Id] UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() NOT NULL,
[ClubId] UNIQUEIDENTIFIER NOT NULL,
[FirstName] NVARCHAR(500) NOT NULL,
[LastName] NVARCHAR(500) NOT NULL,
[MobileNumber] NVARCHAR(250) NULL,
[Email] NVARCHAR(500) NULL,
[CoachCardId] NVARCHAR(500),
[IssueDate] DATETIME NULL,
[CardImage] VARBINARY(max) NULL,
[Qualifications] NVARCHAR(1000) NULL,
[DateCreated] DATETIME NOT NULL DEFAULT GETDATE())