CREATE TABLE [dbo].[Goal](
[Id] BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
[MatchId] BIGINT NOT NULL,
[ScorerPlayerId] UNIQUEIDENTIFIER NOT NULL,
[AssistPlayerId] UNIQUEIDENTIFIER NULL,
[Minute]  INTEGER NULL DEFAULT 0,
[DateCreated] DATETIME NOT NULL DEFAULT GETDATE())
GO