
CREATE TABLE Player(
[Id] UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() NOT NULL PRIMARY KEY,
[MatchId] INTEGER NOT NULL,
[PlayerCardId] NVARCHAR(500),
[IssueDate] DATETIME NULL,
[CardImage] VARBINARY(max) NULL,
[TeamId] UNIQUEIDENTIFIER,
[PositionId] INTEGER NOT NULL,
[FirstName]  NVARCHAR(250) NOT NULL,
[LastName] NVARCHAR(250) NOT NULL,
[ShirtNumber] INTEGER NULL,
[UserId] UNIQUEIDENTIFIER NOT NULL,
[IsDeleted] BIT NOT NULL DEFAULT 0,
[InputDate] DATETIME NOT NULL DEFAULT GETDATE(),
[ProfileImage]  VARBINARY(max) NULL,
[Height] DECIMAL NOT NULL DEFAULT 0,
[Weight] DECIMAL NOT NULL DEFAULT 0,
[StrongFoot] INTEGER NOT NULL DEFAULT 0,
[RatingCount] INTEGER NOT NULL DEFAULT 0,
[RatingSum] INTEGER NOT NULL DEFAULT 0,
[Mom_Count] INTEGER NOT NULL DEFAULT 0,
[DateCreated] DATETIME NOT NULL DEFAULT GETDATE())
GO
