CREATE TABLE [dbo].Stadium(
[Id] UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() NOT NULL,
[Name] NVARCHAR(2000) NOT NULL,
[Address] NVARCHAR(2000) NOT NULL,
[gpsLocation] NVARCHAR(200) NULL,
[DateCreated] DATETIME NOT NULL DEFAULT GETDATE())
GO