
CREATE TABLE [dbo].Stadium(
[Id] UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() NOT NULL,
[Name] NVARCHAR(2000) NOT NULL,
[PhoneNumber] NVARCHAR(250) NULL,
[Address] NVARCHAR(2000) NOT NULL,
[Country] NVARCHAR(250) NULL,
[URL] NVARCHAR(1500) NULL,
[gpsLocation] NVARCHAR(200) NULL,
[DateCreated] DATETIME NOT NULL DEFAULT GETDATE())
GO