CREATE TABLE [dbo].[Statistics](
[Id] BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
[MatchId] BIGINT  NOT NULL,
[GoalsFor] INTEGER NOT NULL DEFAULT 0,
[GoalsAgainst] INTEGER NOT NULL DEFAULT 0,
[Win] BIT NOT NULL DEFAULT 0,
[Draw] BIT NOT NULL DEFAULT 0,
[Lose] BIT NOT NULL DEFAULT 0,
[MOM_PlayerId] UNIQUEIDENTIFIER NULL,
[DateCreated] DATETIME NOT NULL DEFAULT GETDATE())
GO