CREATE TABLE [dbo].Team(
[Id]  UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
[TeamName] NVARCHAR(500) NOT NULL,
[CoverImage]  VARBINARY(max) NULL,
[DateEstablished] DATETIME NOT NULL,
[AvgAge] DECIMAL NOT NULL,
[Skilllevel NVARCHAR(250) NOT NULL,
[UniformColor] NVARCHAR(250) NOT NULL,
[DateCreated] DATETIME NOT NULL DEFAULT GETDATE())
 GO