CREATE TABLE [Training](
[id] INTEGER IDENTITY(1,1) NOT NULL PRIMARY KEY,
[ClubId] UNIQUEIDENTIFIER NULL,
[CoachId] UNIQUEIDENTIFIER NULL,
[gpsLocation] NVARCHAR(200) NULL,
[Date] DATETIME NOT NULL DEFAULT GETDATE(),
[DateCreated] DATETIME NOT NULL DEFAULT GETDATE())
GO