CREATE TABLE [dbo].[Users](
[Id]  UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() NOT NULL PRIMARY KEY,
[UserId] NVARCHAR(450) NULL, --ASPNETUSER
[TeamId] UNIQUEIDENTIFIER NOT NULL,
[UserName] NVARCHAR(500) NOT NULL,
[Password] NVARCHAR(500) NOT NULL,
[FirstName] NVARCHAR(500) NOT NULL,
[LastName] NVARCHAR(500) NOT NULL,
[ProfileImage]  VARBINARY(max) NULL,
[Email] NVARCHAR(500) NOT NULL,
[IsloggedIn] BIT NOT NULL DEFAULT 0,
[DateCreated] DATETIME NOT NULL DEFAULT GETDATE())
GO